// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXzShhX5eXhCAxBI0LKYZHX01R7_vpmCI',
    appId: '1:899488201348:web:e8898eaa6eadb6b37720d1',
    messagingSenderId: '899488201348',
    projectId: 'quizwhizz-b593e',
    authDomain: 'quizwhizz-b593e.firebaseapp.com',
    storageBucket: 'quizwhizz-b593e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgJTRczcOl_K5xiF70PsCKvGIv3Kq0a3g',
    appId: '1:899488201348:android:23bc2621b841d6627720d1',
    messagingSenderId: '899488201348',
    projectId: 'quizwhizz-b593e',
    storageBucket: 'quizwhizz-b593e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGvdQ_R4bPxvoIT1QrZVmNhZCqqzpqrbQ',
    appId: '1:899488201348:ios:49d8ce7f6cb0f82e7720d1',
    messagingSenderId: '899488201348',
    projectId: 'quizwhizz-b593e',
    storageBucket: 'quizwhizz-b593e.appspot.com',
    androidClientId: '899488201348-8roa2ps27l56ubl25t4a3sskit6qfsct.apps.googleusercontent.com',
    iosClientId: '899488201348-uhja4n8v0t0b0acoifnr9ln19g8ull3q.apps.googleusercontent.com',
    iosBundleId: 'com.tdtu.da2.g160.whizz',
  );
}
